# Generated by Django 3.0.4 on 2020-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190412_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_summary',
            field=models.TextField(),
        ),
    ]
