# Generated by Django 3.0.4 on 2020-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200406_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='tutorial_image',
            field=models.ImageField(default='https://www.flip-transfer.com/assets/img/drop.png', upload_to=''),
        ),
    ]
