# Generated by Django 3.0.4 on 2020-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tutorialcategory_tutorial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcategory',
            name='tutorial_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
